# Generated by Django 4.1.3 on 2022-11-06 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='familia',
            name='nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
