# Generated by Django 4.1.3 on 2022-11-06 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0002_familia_nacimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='familiares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('edad', models.IntegerField()),
                ('nacimiento', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='familia',
        ),
    ]
